### ISSUE TITLE
Problem importing the package 

### ISSUE THREAD

**Issue by danielguerreros** [znstrider/plottable#2]
I have tried to use this package but all the times I try to import it I get the following error.

TypeError                                 Traceback (most recent call last)
Cell In [2], line 1
----> 1 from plottable import Table

File ~/miniforge3/envs/plot-tables/lib/python3.9/site-packages/plottable/__init__.py:4
      1 __version__ = "0.1.3"
      3 from .column_def import ColDef, ColumnDefinition, ColumnType
----> 4 from .table import Table

File ~/miniforge3/envs/plot-tables/lib/python3.9/site-packages/plottable/table.py:15
     13 from .column_def import ColumnDefinition, ColumnType
     14 from .font import contrasting_font_color
---> 15 from .formatters import apply_string_formatter
     16 from .helpers import _replace_lw_key
     19 class Table:

File ~/miniforge3/envs/plot-tables/lib/python3.9/site-packages/plottable/formatters.py:4
      1 from numbers import Number
----> 4 def apply_string_formatter(fmt: str, val: str | Number) -> str:
      5     return fmt.format(val)
      8 def decimal_to_percent(val: float) -> str:

TypeError: unsupported operand type(s) for |: 'type' and 'ABCMeta'

I have tried to create an empty environment and installing only the package and still get the same problem

**Comment by znstrider** [comment]
You are not the first to report this issue. You need python>= 3.10 for plottable at the moment, due to the use of the `|` operator in the typing syntax. I wasn't aware of that at first unfortunately. For now I updated the requirements to reflect this.

**Comment by znstrider** [comment]
I am considering to change this to enable people with python<3.10 to use plottable. If you come across this error, add a reaction to this comment.
